Fix a deadlock.  This makes kernel compile last much much longer until I hit the following:
drivers/input/touchscreen/ad7879-spi.c:164:1: fatal error: closing dependency file drivers/input/touchscreen/.ad7879-spi.o.d: Numerical result out of range
 MODULE_ALIAS("spi:ad7879");
 ^
compilation terminated.
The bug is not reproducible, so it is likely a hardware or OS problem.

I also saw the following at the same time:

[1433360966:409002 msnbrqthr1:7ffef4ff9700:rpc rpcclient.c pscrpc_check_status 485] req@0x7ffe6000b3b0 x6985989/t0 cb=0x417b21 c0
o42->@54321-128.182.99.27@tcp10:30 lens 264/192 ref 1 res 0 ret 0 fl Rpc:R/0/0 replyc 0 rc 0/-501 to=58 sent=1433360966 :: type == PSCRPC_MSG_ERR, rc == -501