More compilation fixes.  Everything compiles now with only 1 warning: offtree.c: In function ‘offtree_putnode’: offtree.c:399: warning: implicit declaration of function ‘sl_oftm_addref’
Made 1 significant structural change.  A tree node now has a op_ref count instead of a REQPNDG flag.  This will allow for tracking of multiple pending requests as opposed to just 1.



git-svn-id: svn+ssh://frodo/cluster/svn/projects/slash_nara@2916 3eda493b-6a19-0410-b2e0-ec8ea4dd8fda